use javadb;
-- 创建class 表
create table classes
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;

-- 创建students表
create table students
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT,
    CLASS_ID BIGINT       NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    GENDER   VARCHAR(1)   NOT NULL,
    SCORE    INT          NOT NULL,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;

create table user (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    TEL VARCHAR (200) NOT NULL UNIQUE,
    ADDRESS VARCHAR (100),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
) DEFAULT CHARSET=utf8;

create table goods(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
) DEFAULT CHARSET=utf8;

create table `order`(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    GOODS_ID BIGINT,
    GOODS_NUM INT,
    GOODS_PRICE DECIMAL NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
) DEFAULT CHARSET=utf8;
